version: '3.7'

services:

  db:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - db
    
  react: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        API_DOMAIN_NAME: ${API_DOMAIN_NAME}
    depends_on: 
      - django