version: '3.7'

services:

  django:
    volumes:
      - ./backend:/usr/src/backend
    command: sh -c 'python manage.py migrate && python -m uvicorn core.asgi:application --host 0.0.0.0 --port 8000'
    ports: 
      - 8000:8000
    
  react: 
    volumes:
      - ./frontend:/usr/src/frontend
    command: npm start
    ports:
      - 3000:3000

