# Generated by Django 4.2.6 on 2023-10-19 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users who follows the user'),
        ),
        migrations.AddField(
            model_name='user',
            name='tracks',
            field=models.ManyToManyField(to='music.track', verbose_name='Tracks which added by user'),
        ),
    ]
