# Generated by Django 4.2.6 on 2023-11-17 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='streams',
        ),
        migrations.AddField(
            model_name='track',
            name='streams',
            field=models.ManyToManyField(related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
