# Generated by Django 4.2.6 on 2023-11-27 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0002_track_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="streams",
            field=models.ManyToManyField(
                null=True, related_name="streams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
