# Generated by Django 4.2.6 on 2023-11-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to='track_images'),
        ),
    ]
