# Generated by Django 4.2.6 on 2023-11-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_alter_track_file_alter_track_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="author",
            new_name="uploader",
        ),
    ]
