# Generated by Django 4.2.6 on 2023-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0007_rename_author_track_uploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="author",
            field=models.CharField(default="Radmir Askarov", max_length=255),
        ),
    ]
