# Generated by Django 4.2.6 on 2023-11-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("TRACK_ADD", "Track added"),
                            ("TRACK_UPLOAD", "Track uploaded"),
                            ("PLAYLIST_CREATE", "Playlist created"),
                            ("FOLLOWING_START", "Following started"),
                        ],
                        verbose_name="Reason of update, for example downloading a track",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
